var loja={
    nome: "Shuri's store",
    aluguelDia: 350,
    gastoEnergia: 80,
    gastoAgua: 40,
    impostoEmPorcentagem: 15,
    seguroDia: 300,
    valorInvestido: 500000,
    quantDiasFuncionais: 26,
    quantHorasFuncionais: 16,

    funcionarios:[{
        nome: "Guilherme",
        salarioHora: 7,
        emissao: new Date("2022-12-13"),
        vrDia: 7,
        vtDia: 10,
        planoSaudeDia: null,
        horasTrabalhadasDia: 8,
        cargo: "Faxina",
        turno: "Sempre",
    },
    {
        nome: "Antonio",
        salarioHora: 7,
        emissao: new Date("2022-12-13"),
        vrDia: 7,
        vtDia: 10,
        planoSaudeDia: null,
        horasTrabalhadasDia: 8,
        cargo: "Faxina",
        turno: "Tarde",
    },
    {
        nome: "Zoe",
        salarioHora: 7,
        emissao: new Date("2022-12-13"),
        vrDia: 7,
        vtDia: 10,
        planoSaudeDia: 15,
        horasTrabalhadasDia: 8,
        cargo: "Caixa",
        turno: "Manhã",
    },
    {
        nome: "Maria",
        salarioHora: 7,
        emissao: new Date("2022-12-13"),
        vrDia: 7,
        vtDia: 10,
        planoSaudeDia: 15,
        horasTrabalhadasDia: 8,
        cargo: "Caixa",
        turno: "Tarde",
    },
    {
        nome: "Marco",
        salarioHora: 7,
        emissao: new Date("2022-12-13"),
        vrDia: 7,
        vtDia: 10,
        planoSaudeDia: 15,
        horasTrabalhadasDia: 8,
        cargo: "Repositor",
        turno: "Manhã",
    },
    {
        nome: "João",
        salarioHora: 7,
        emissao: new Date("2022-12-13"),
        vrDia: 7,
        vtDia: 10,
        planoSaudeDia: 15,
        horasTrabalhadasDia: 8,
        cargo: "Repositor",
        turno: "Tarde",
    }
]
}

exports.loja=loja ;